### ISSUE TITLE
Directory structure change request.

### ISSUE THREAD

**Issue by ltdrdata** [Beinsezii/bsz-cui-extras#1]
Currently, the files are placed within the `bsz-nodes` subdirectory. In this case, it's not possible to install it simply by using `git clone`.

If we individually download and move the files, we won't be able to handle situations like updates. I would recommend that you move the files from the `bsz-nodes` directory to the root directory to address this.

Also, there's a `centerizer.py` file inside the workflow folder. Is that intentional?

Thank you.

**Comment by Beinsezii** [comment]
Far as I know you can't install it with a clone anyways because you can't clone into an existing repo. Placing them in `bsz-nodes` was done specifically to make updating via git easier, because you can clone the repo outside of ComfyUI then just symlink the whole `bsz-nodes` folder into ComfyUI's `custom_nodes`. That makes updating a simple git pull.

**Comment by ltdrdata** [comment]
> Far as I know you can't install it with a clone anyways because you can't clone into an existing repo. Placing them in `bsz-nodes` was done specifically to make updating via git easier, because you can clone the repo outside of ComfyUI then just symlink the whole `bsz-nodes` folder into ComfyUI's `custom_nodes`. That makes updating a simple git pull.

Generally, most of the custom node repositories managed by ComfyUI-Manager have a structure with an `__init__.py` in the root. With this structure, when you clone `bsz-nodes` into `custom_nodes`, the directory structure becomes `custom_nodes/bsz-nodes`, and it can be naturally utilized in ComfyUI.

Furthermore, placing something outside the path of ComfyUI in the management program is highly inappropriate, so it's not a viable option.

**Comment by Beinsezii** [comment]
This isn't just a node repository though, it also has workflows. The root of my nodes folder has the init script like you'd expect.

> Furthermore, placing something outside the path of ComfyUI in the management program is highly inappropriate, so it's not a viable option.

What does this even mean? What is this "management program" and how does it make a simple

`ln -s ./bsz-cui-extras/bsz-nodes/ ./custom-nodes/`

inappropriate and unviable?

**Comment by ltdrdata** [comment]
> What does this even mean? What is this "management program" and how does it make a simple
> 
> `ln -s ./bsz-cui-extras/bsz-nodes/ ./custom-nodes/`
> 
> inappropriate and unviable?

Oh, I should have mentioned this earlier. I forgot. I apologize.
https://github.com/ltdrdata/ComfyUI-Manager

The use of methods like `ln -s` is strongly discouraged. This is due not only to the fact that handling symbolic links differs across platforms, but also because, in order to employ such an approach, `ComfyUI-Manager` would need to clone into a hidden directory that users might not be aware of, and then link it to the `custom_nodes` path. However, this would only increase management complexity without providing any benefits.

**Comment by Beinsezii** [comment]
I added a 2nd init script hardcoded to forward `bsz-nodes` at the root of my repo in https://github.com/Beinsezii/bsz-cui-extras/commit/63dd6139f343a555756d9032c8bffd48d481a853

You can now put the whole repo in `/custom_nodes/` and it loads fine, so I assume that fixes the compatibility issue with your manager?

**Comment by Beinsezii** [comment]
Also to answer your earlier question `centerizer.py` centers workflow files on the comfyui grid. I committed it to the repo so if someone edits the workflows they can recenter them.

**Comment by Beinsezii** [comment]
With 66596c1e0be0ffc34d0e6c917dacfd9468a5294e and f96becf5671257c48ba4b928971ec7d705c37955 everything in the repo should work out-of-the-box when cloned directly into `/custom_nodes/` and is fully update-able with a pull.
